# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NestUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1081, 768)
        Form.setToolTip("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 187, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.list = QtWidgets.QListView(self.verticalLayoutWidget)
        self.list.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.list.setObjectName("list")
        self.verticalLayout.addWidget(self.list)
        self.pushButton_select = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_select.setObjectName("pushButton_select")
        self.verticalLayout.addWidget(self.pushButton_select)
        self.pushButton_dxf = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_dxf.setObjectName("pushButton_dxf")
        self.verticalLayout.addWidget(self.pushButton_dxf)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Docx = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Docx.setObjectName("pushButton_Docx")
        self.horizontalLayout.addWidget(self.pushButton_Docx)
        self.isNeedMaterialList = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.isNeedMaterialList.setObjectName("isNeedMaterialList")
        self.horizontalLayout.addWidget(self.isNeedMaterialList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_summarize = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_summarize.setObjectName("pushButton_summarize")
        self.verticalLayout.addWidget(self.pushButton_summarize)
        self.pushButton_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.pushButton_Help = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Help.setObjectName("pushButton_Help")
        self.verticalLayout.addWidget(self.pushButton_Help)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 20, 831, 731))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.infoTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.infoTable.setFont(font)
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(10)
        self.infoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.infoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(9, item)
        self.infoTable.horizontalHeader().setMinimumSectionSize(18)
        self.infoTable.horizontalHeader().setSortIndicatorShown(True)
        self.infoTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.infoTable)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.filterTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filterTable.setFont(font)
        self.filterTable.setObjectName("filterTable")
        self.filterTable.setColumnCount(8)
        self.filterTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.filterTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.filterTable.setHorizontalHeaderItem(7, item)
        self.filterTable.horizontalHeader().setMinimumSectionSize(18)
        self.filterTable.horizontalHeader().setSortIndicatorShown(True)
        self.filterTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.filterTable)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.errorTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.errorTable.setObjectName("errorTable")
        self.errorTable.setColumnCount(5)
        self.errorTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.errorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.errorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.errorTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.errorTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.errorTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.errorTable)

        self.retranslateUi(Form)
        self.pushButton_select.clicked.connect(Form.selectExcel)
        self.pushButton_dxf.clicked.connect(Form.letDxfWork)
        self.pushButton_clear.clicked.connect(Form.clear)
        self.pushButton_Docx.clicked.connect(Form.letDocxWork)
        self.pushButton_summarize.clicked.connect(Form.summarize)
        self.pushButton_Help.clicked.connect(Form.helpInfo)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "目标路径："))
        self.pushButton_select.setToolTip(_translate("Form", "<html><head/><body><p>输入规定格式的EXCEL表格</p></body></html>"))
        self.pushButton_select.setText(_translate("Form", "选择文件"))
        self.pushButton_dxf.setToolTip(_translate("Form", "<html><head/><body><p>根据EXCEL表格中数据生成CAD格式（DXF）的文件</p></body></html>"))
        self.pushButton_dxf.setText(_translate("Form", "生成dxf"))
        self.pushButton_Docx.setToolTip(_translate("Form", "<html><head/><body><p>生成标准化下料清单</p></body></html>"))
        self.pushButton_Docx.setText(_translate("Form", "生成下料清单"))
        self.isNeedMaterialList.setText(_translate("Form", "包含板材清单"))
        self.pushButton_summarize.setToolTip(_translate("Form", "<html><head/><body><p>将相同厚度DXF文件汇总至一个文件夹</p></body></html>"))
        self.pushButton_summarize.setText(_translate("Form", "文件汇总"))
        self.pushButton_clear.setToolTip(_translate("Form", "<html><head/><body><p> 清除所有已生成的文件信息</p></body></html>"))
        self.pushButton_clear.setText(_translate("Form", "清除"))
        self.pushButton_Help.setText(_translate("Form", "帮助"))
        self.label_5.setText(_translate("Form", "已绘制的零件明细："))
        item = self.infoTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "文件号"))
        item = self.infoTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "序号"))
        item = self.infoTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "名称"))
        item = self.infoTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "属性1"))
        item = self.infoTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "属性2"))
        item = self.infoTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "属性3"))
        item = self.infoTable.horizontalHeaderItem(6)
        item.setText(_translate("Form", "材料"))
        item = self.infoTable.horizontalHeaderItem(7)
        item.setText(_translate("Form", "厚度"))
        item = self.infoTable.horizontalHeaderItem(8)
        item.setText(_translate("Form", "数量"))
        item = self.infoTable.horizontalHeaderItem(9)
        item.setText(_translate("Form", "备注"))
        self.label_6.setText(_translate("Form", "略去的零件明细："))
        item = self.filterTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "文件号"))
        item = self.filterTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "序号"))
        item = self.filterTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "名称"))
        item = self.filterTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "属性1"))
        item = self.filterTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "属性2"))
        item = self.filterTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "属性3"))
        item = self.filterTable.horizontalHeaderItem(6)
        item.setText(_translate("Form", "数量"))
        item = self.filterTable.horizontalHeaderItem(7)
        item.setText(_translate("Form", "备注"))
        self.label_7.setText(_translate("Form", "报错信息："))
        item = self.errorTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "文件号"))
        item = self.errorTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "序号"))
        item = self.errorTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "名称"))
        item = self.errorTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "代号"))
        item = self.errorTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "错误描述"))

